x-team/unleash

- app/styles/pages/_edit.scss
- app/views/edit.html
https://github.com/x-team/unleash/pull/25
> #23 "Go back to *** profile" is off + it directs to a wrong URL

- app/scripts/directives/achieve.js
> Revert "'Mark as achieved' button doesn't work..."

- app/scripts/directives/achieve.js
> mark as achievded worked only when user edit own card

- app/index.html
- app/scripts/angularfire/firebase.utils.js
- app/scripts/controllers/edit.js
- app/scripts/directives/templateedit.js
- app/scripts/services/cards.js
- app/scripts/services/comments.js
- app/scripts/services/debug.js
- app/scripts/services/templates.js
- bower.json
As we decided, I updated the AngularFire to version 1.1, Firebase to 2.2. Might solve issues connected with firebase, please check :)
> Angularfire 1.1 firebase update

- app/scripts/directives/pathbg.js
- app/views/partials/pathbg.html
PR that includes only issue #63 changes. @theanxy please check, if that's okay now, thanks :+1:
> Issue #63 dynamic user path

- app/styles/modules/_card.scss
- app/styles/pages/_edit.scss
- app/views/edit.html
- app/views/partials/card.html
- app/views/partials/path.html
As asked in issue #69, I added a description of a card.
Note: @kbdbrnwsk asked me to add the descriptions on both sides (template cards and cards in drop area). I had to enlarge the cards, as agreed with @kbdbrnwsk.
> Issue #69 - cards with description in path edit

- Gruntfile.js
- app/index.html
- app/scripts/controllers/edit.js
- app/scripts/directives/cardsadd.js
- app/scripts/directives/scrollbookmark.js
- app/scripts/directives/sticky.js
- app/scripts/services/cards.js
- app/styles/modules/_card.scss
- app/styles/pages/_edit.scss
- app/views/edit.html
- app/views/partials/cardsAdd.html
- test/spec/directives/cardsadd.js
- test/spec/directives/sticky.js
> Add option to create quick cards in path edit view

- .gitignore
- Dockerfile
- Gruntfile.js
- README.md
- app/styles/_common.scss
- app/styles/main.scss
- bower.json
- docker-compose.yml
- package.json
- Moved the project to run as a Docker container
- updated components versions
- updated docs
This might be helpful to run the app on local machines without having to install everything locally. Just to have the whole thing out-of-the-box :)
> Moved the project to run on Docker

- app/styles/_common.scss
- app/styles/_mixins.scss
- app/views/home.html
- app/views/path.html
When you get on the page it's most of the time empty until the content loads - may take some time - so a good idea would be to add a spinner there.
Sorry for the gif quality but you should get the idea:
@jkbdbrnwsk - what you say?
> Added a loading spinner

- .gitignore
- Gruntfile.js
- app/index.html
- app/scripts/constants-template.js
- app/scripts/constants.js
- app/scripts/directives/achieve.js
- app/scripts/directives/carddetails.js
- app/scripts/services/comments.js
- app/scripts/services/mail.js
- app/scripts/services/slack.js
- app/scripts/services/user.js
- app/styles/modules/_achievements.scss
- app/views/partials/achieve.html
- app/views/partials/cardDetails.html
PR contains improvements in commenting system, as asked in issue #68. Due to connected issues #37 and #38, I decided to put them together.
One can now add replies to existing comments in user's cards. Apart from that, such notifications are being sent:
- mail to Card Owner, if someone comments,
- mail to Card Owner, if someone replies to comment,
- mail to Comment Author, if someone replies to his/her comment.
Please note that the notification is not sent, if:
- Card Owner made a comment on his/her card,
- Card Owner replied to a comment on his/her card,
- Comment Author replied to his/her comment.
In the situation when someone replied to a comment and Card Owner and Comment Author is the same user, only one notification is sent.
The content of the message that is being sent is still …
> Improving commenting system

- Gruntfile.js
- app/index.html
- app/scripts/app.js
- app/scripts/directives/card.js
- app/scripts/directives/carddetails.js
- app/scripts/services/cards.js
- app/styles/_common.scss
- app/styles/main.scss
- app/styles/modules/_achievements.scss
- app/styles/modules/_card.scss
- app/styles/pages/_edit.scss
- app/styles/pages/_path.scss
- app/views/partials/card.html
- app/views/partials/cardDetails.html
- app/views/partials/cardsAdd.html
- bower.json
- test/karma.conf.js
- test/spec/directives/auth.js
- test/spec/directives/card.js
This PR adds a feature, that lets the admin or the card owner set a due date to the associated achievement. The due date is displayed on the card.
Coming next: Slack notifications, that will be sent, when a card is nearing it's due date.
I discovered some errors in some other tests(auth directive), so I fixed them as well.
> Add due date

- app/scripts/directives/carddetails.js
- app/scripts/services/slack.js
- app/scripts/services/user.js
- app/styles/modules/_achievements.scss
- app/views/partials/achieve.html
- Switched to attachments to render notifications in a nicer way
> Refactoring, updates for 'card achieved' notifications

- Gruntfile.js
- app/index.html
> Fixes #85 - Due Date calendar styling fix

- app/scripts/directives/carddetails.js
- app/scripts/services/comments.js
- app/scripts/services/mail.js
> Switch to full names in email notifications

- app/styles/pages/_edit.scss
- app/views/partials/cardsAdd.html
> Fix due date field in quick cards

- app/index.html
- app/scripts/directives/persons.js
- app/views/home.html
- app/views/partials/persons.html
Refactored the list of people into a directive which you can pass the array of users to render to as an argument.
Will need this on the skill view for list of poeple associated with a skill.
> Refactored list of people into a directive

- app/scripts/services/mail.js
> Update email sender's name

- app/scripts/services/slack.js
> Wording improvements for slack notifications

- app/scripts/directives/carddetails.js
- app/styles/modules/_achievements.scss
- app/views/partials/cardDetails.html
Fixes #122 
- Let admins unset card's due date
- Nicer styling for admin settings
- Fixed a bug where "Edit this path" link was causing links on the same (e.g. mark as achieved) line to not work
> Let admins unset card's due date

- app/scripts/services/cards.js
> Clear the list of sent notifications once duedate is updated

- app/index.html
- app/scripts/directives/template.js
- app/scripts/services/cards.js
- app/views/edit.html
- app/views/partials/template.html
> Fix assigning templates as cards to users

- Gruntfile.js
- app/scripts/constants-template.js
- app/scripts/controllers/edit.js
- app/scripts/controllers/path.js
- app/scripts/directives/achieve.js
- app/scripts/directives/card.js
- app/scripts/directives/carddetails.js
- app/scripts/directives/cardsadd.js
- app/scripts/services/cards.js
- app/scripts/services/comments.js
- app/scripts/services/slack.js
- app/views/edit.html
- app/views/partials/card.html
- app/views/partials/cardDetails.html
- app/views/partials/cardsAdd.html
- app/views/partials/path.html
- test/spec/directives/card.js
- test/spec/directives/cardsadd.js
> Refactor unleash paths

- app/views/partials/card.html
> Fix showing comments icon on card

- app/index.html
Fixed loading google api asynchronously with defer option
> Fix Google API defer

- app/scripts/services/comments.js
- app/views/partials/cardDetails.html
> Fix commenting and replying

- app/views/partials/path.html
> Fix loader

- app/scripts/controllers/edit.js
- app/scripts/controllers/path.js
- app/scripts/controllers/templates.js
- app/scripts/directives/templateedit.js
- app/scripts/services/templates.js
- app/styles/pages/_templates.scss
- app/views/edit.html
- app/views/partials/templateAdd.html
- app/views/partials/templateEdit.html
- app/views/path.html
- app/views/templates.html
> Add Pool of Goals

- app/index.html
- app/scripts/app.js
- app/scripts/services/user.js
- app/views/home.html
- bower.json
- test/karma.conf.js
- test/spec/routes.js
- test/spec/routes.loggedin.js
> Add loading spinner while authenticating and logged in previously

- app/index.html
- app/scripts/controllers/edit.js
- app/scripts/directives/card.js
- app/scripts/services/cards.js
- app/styles/modules/_card.scss
- app/styles/pages/_edit.scss
- app/views/edit.html
- app/views/partials/card.html
Fixes #147 
Demo: http://d.pr/i/17ad1
> Feature/edit parallel paths #147

- app/scripts/controllers/edit.js
- app/scripts/services/cards.js
> Fix reordering cards

- app/views/partials/card.html
> Fix remove label

- app/views/partials/userpaths.html
> Fix displaying empty paths

- app/scripts/controllers/edit.js
- app/scripts/directives/cardsadd.js
- app/views/partials/cardsAdd.html
- test/spec/directives/cardsadd.js
> Add feature of selecting paths during quick cards adding

- app/scripts/directives/achieve.js
- app/scripts/services/slack.js
> Fix query string for achievement notifications

- .eslintrc
- app/App.js
- app/actions/SkillActions.js
- app/components/Goals.js
- app/components/Menu.js
- app/components/Path.js
- app/components/Paths.js
- app/components/Skill.js
- app/components/Skills.js
- app/components/UnleashApp.js
- app/config/routes.js
- app/reducers/rootReducer.js
- app/reducers/skillsReducer.js
- package.json
- webpack.config.js
**Issue #204**:
- adds eslint 2.9 with airbnb preset,
- fixes errors in the code,
Does not fix those errors:
```Component should be written as a pure function  react/prefer-stateless-function```
Since those components will for sure be extended.
> Add eslint setup

- .eslintrc
- .gitignore
- app/actions/SkillActions.js
- config.dist.js
- package.json
- webpack.config.js
I [developed this plugin](https://github.com/rmariuzzo/config-webpack-plugin) to initially fit our needs. This plugin intercept a configuration file and replace any key that matches a ken in the `process.env` field (environment variables).
---
Note: This fixes #212.
> Using `config-webpack-plugin` to process our config file and more

- app/actions/ProfileActions.js
- app/components/Menu.js
- app/components/Paths.js
- app/components/Profiles.js
- app/components/UnleashApp.js
- app/components/__tests__/Profiles.spec.js
- app/config/routes.js
- app/reducers/profilesReducer.js
- app/reducers/rootReducer.js
- app/testUtils/fixtures/index.js
- app/testUtils/fixtures/profile.js
- app/testUtils/fixtures/skill.js
- config.dist.js
Added simple profiles list with specs
> Add profiles list

- .travis.yml
> Add basic tests on Travis

- app/actions/PathsActions.js
- app/components/Path.js
- app/reducers/pathsReducer.js
- app/reducers/rootReducer.js
- config.dist.js
- package.json
> Add user Paths - fixes #224

- .gitignore
- app/actions/PathsActions.js
- app/actions/ProfileActions.js
- app/actions/SkillActions.js
- app/actions/__tests__/PathsActions.spec.js
- app/actions/__tests__/ProfileActions.spec.js
- app/actions/__tests__/SkillActions.spec.js
- app/components/__tests__/Goals.spec.js
- app/components/__tests__/Menu.spec.js
- app/components/__tests__/Path.spec.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skill.spec.js
- app/components/__tests__/Skills.spec.js
- app/testUtils/fixtures/index.js
- app/testUtils/fixtures/path.js
- app/testUtils/setup.js
- package.json
-Added test to components.
-Added test to actions.
-Added paths faker.
-Added nyc package for code coverage.
-Added nock to mock HTTP request.
-Added asset-require-hook for the images file when the test run.
-Added fetch for JSDOM to make fetch HTTP request.
> Added test and coverage - fixes #233

- app/components/Path.js
- app/components/Profiles.js
- app/components/Skills.js
- app/components/__tests__/Path.spec.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skills.spec.js
- app/config/routes.js
- app/containers/GoalsContainer.js
- app/containers/PathContainer.js
- app/containers/ProfilesContainer.js
- app/containers/SkillContainer.js
- app/containers/SkillsContainer.js
Separated components so presentational components don't depend on state or context, their sole purpose now is to render and behave based on passed props. Container will handle the rest.
View #234 for more info.
> Separate Components into Presentational and Containers - fixes #234

- app/actions/ProfileActions.js
- app/components/Path.js
- app/components/Profiles.js
- app/components/__tests__/Path.spec.js
- app/config/routes.js
- app/containers/PathContainer.js
> Load User Paths from direct URL

- app/store/configureStore.js
- package.json
-Added the Redux dev extension for easier development process and time travel.
-Remove redux-logger.
> Add Redux DevTools Extension

- app/App.js
-Added fetch polyfill to support browsers without fetch.
> Use Fetch Polyfill - Fixes #254

- app/actions/ProfileActions.js
- app/actions/SkillActions.js
- app/actions/__tests__/ProfileActions.spec.js
- app/actions/__tests__/SkillActions.spec.js
- app/components/Loading.js
- app/components/Profiles.js
- app/components/Skill.js
- app/components/Skills.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skill.spec.js
- app/components/__tests__/Skills.spec.js
- app/config/routes.js
- app/containers/SkillContainer.js
- app/reducers/profilesBySkillReducer.js
- app/reducers/profilesReducer.js
- app/reducers/rootReducer.js
- app/reducers/skillsReducer.js
~~**DO NOT MERGE**~~
This is a working version~~, no yet clean or stable~~. I'm willing to receive feedback as my first contribution.
Credits to @kdemoya for the styling I grabbed from one of his recent PR.
1. When the user click on a skill, while fetching the profiles the component renders: “no profiles for this skill yet...” then after a short time the results appears (if any). I understand why this happens, but I would like to know what is the best approach to deal with data that is still loading. State?
**DO NOT MERGE**
> Added profiles by skill.

- app/components/Profiles.js
- app/components/Skill.js
- app/components/UserCard.js
- app/components/__tests__/Goals.spec.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skill.spec.js
- app/components/__tests__/UserCard.spec.js
Created new `UserCard` component to render users anywhere on the app with the user object from the API.
Looking at all those default images it came to my mind that we should have a default hero that we can use when a user have the default gmail image or have no image at all. What do you guys think? @karolsojko @jkbdbrnwsk @ryanchartrand @jacekelgda
> Add Profiles Style - fixes #223

- app/actions/user/UserReducerFunctions.js
- app/components/Menu.js
- app/components/__tests__/Menu.spec.js
- app/containers/Menu.js
> My Path #248

- app/components/GoalCard.js
- app/components/Path.js
- app/components/__tests__/GoalCard.spec.js
- app/hocs/__tests__/toggleHOC.spec.js
- app/hocs/toggleHOC.js
- app/testUtils/fixtures/goal.js
> Add dialog with details on goals component - fixes #249

- app/styles/modules/_card.scss
- app/views/partials/card.html
> Proposal: Style of cards to edit - added icons and expanded height

- README.md
Numbered list was fixed so it renders properly. Also syntax highlighting
added in code blocks. Finally, minor typos were addressed.
This fixes #284.
> Improved formatting.

- app/components/Skill.js
**DO NOT MERGE**
The idea is to show resources in a second plane after profiles. Using tabs
we can achieve this separation of contents. 
[![maxresdefault](https://cloud.githubusercontent.com/assets/439839/19026629/2cca6c08-88f6-11e6-8801-adeac4ae7338.jpg)](https://youtu.be/FfE_JODRHJk)
---
This could/eventually closes #269.
> Added proposal for skill's resources.

- app/actions/PathsActions.js
- app/actions/__tests__/PathsActions.spec.js
- app/components/Path.js
- app/reducers/pathsReducer.js
- config.js
> Add creating paths feature - fixes #264

- app/actions/ProfileActions.js
- app/components/Profiles.js
- app/components/__tests__/Profiles.spec.js
- app/containers/ProfilesContainer.js
- app/reducers/profilesBySkillReducer.js
- package.json
Added a search bar at the top of profiles (with autocomplete from the list of skills) to search users by skills.
> Added profile search by skill - fixes #268

- app/helpers/__test__/authHelper.spec.js
- app/helpers/authHelper.js
- app/services/authService.js
Anyone should be able to register - not only people with an X-Team email account
Fixes #295
> Add open registration - fixes #295

- app/actions/PathsActions.js
- app/components/Path.js
- app/components/PathHeader.js
- app/reducers/pathsReducer.js
Added renaming feature to Paths, see attached gif for demo.
> Adding Path renaming - fixes #265

- app/components/Goals.js
- app/components/__tests__/Goals.spec.js
Replaced `List` and `ListItem` in Goals views with the `GoalCard` component.
> Updating Goals view to use GoalCard component

- app/actions/PathsActions.js
- app/components/GoalCard.js
- app/components/Path.js
- app/components/__tests__/Path.spec.js
- app/reducers/pathsReducer.js
> Feature: mark a goal as achieved.

- app/actions/ProfileActions.js
- app/components/Path.js
- app/components/Profile.js
- app/config/routes.js
- app/containers/ProfileContainer.js
- app/reducers/profilesReducer.js
> Feature: Render skills in profile

- yarn.lock
Fixed missing yarn dependencies after merging: https://github.com/x-team/unleash/pull/316
/cc @gesposito @kdemoya
> Fix yarn dependencies

- app/actions/SkillActions.js
- app/actions/__tests__/SkillActions.spec.js
- app/components/Skill.js
- app/reducers/skillsReducer.js
- config.js
> Feature: Add resource to Skill

- app/components/Path.js
- app/components/Profile.js
- app/components/__tests__/Path.spec.js
- app/components/__tests__/UserCard.spec.js
- app/containers/ProfileContainer.js
> Add limiting paths creationg to only admins and path owners - fixes #311

- app/components/Skill.js
Pretty simple change. 
API needs to get updated to support resource type and voting.
> Skill resources read real data #292

- app/actions/SkillActions.js
- app/components/AddSkillsModal.js
- app/components/Skills.js
- app/components/__tests__/Skills.spec.js
- app/containers/SkillsContainer.js
- app/reducers/skillsReducer.js
Added Skills create functionality to UI, following how it is done for Goals.
> Creating Skills - fixes #315

- .travis.yml
- app/components/Menu.js
- config.js
> Add version displaying

- app/components/GoalCard.js
- app/components/__tests__/GoalCard.spec.js
> Add updating due date on goals - fixes #307

- app/actions/PathsActions.js
- app/components/AddGoalsModal.js
- app/components/Goals.js
- app/components/Profile.js
- app/containers/ProfileContainer.js
- app/reducers/goalsReducer.js
Fixes #308 
Added creating custom goals for a given path
> Add creating custom goals for a given path - fixes #308

- app/actions/UserActions.js
- app/actions/__tests__/UserActions.spec.js
- app/components/Loading.js
- app/components/Login.js
- app/components/UnleashApp.js
- app/components/__tests__/Login.spec.js
- app/containers/UnleashApp.js
- app/reducers/__test__/userReducer.spec.js
- app/reducers/userReducer.js
- app/services/authService.js
-When we load the Unleash site we can click to login button with a current logged session and show the account select dialog.
> Fix login bug

- app/components/Skill.js
> Add button empty skill resources list --fixes #347

- app/actions/PathsActions.js
- app/components/GoalCard.js
- app/services/slackService.js
- config.js
-Added Slack notification service
-Send message when we mark a card as achieved
> Slack Notification  #343

- app/actions/PathsActions.js
- app/components/AddGoalsModal.js
- app/components/__tests__/AddGoalsModal.spec.js
- app/reducers/goalsReducer.js
> Add due date on goal creation.

- app/actions/GoalsActions.js
- app/actions/NotificationActions.js
- app/actions/PathsActions.js
- app/actions/SkillActions.js
- app/actions/__tests__/NotificationActions.spec.js
- app/components/NotificationBar.js
- app/components/UnleashApp.js
- app/containers/UnleashApp.js
- app/reducers/notificationsReducer.js
- app/reducers/rootReducer.js
- app/services/authService.js
- app/store/configureStore.js
- package.json
> Use material-ui Snackbar instead of toastr - fixes #358

- app/actions/GoalsActions.js
- app/actions/PathsActions.js
- app/components/AddExistingGoalsModal.js
- app/components/AddExistingGoalsModal.jsx
- app/components/Profile.jsx
- app/containers/ProfileContainer.js
- app/reducers/goalsReducer.js
> Add feature for adding existing goals to a path - fixes #344

- app/actions/PathsActions.js
- app/components/GoalCard.jsx
- app/components/Path.jsx
- app/services/httpClient.js
Fixes #357 
Has to be adjusted after merging: https://github.com/x-team/unleash/pull/360
Updated after: https://github.com/x-team/unleash/pull/356
> Add removing goals from a path - fixes #357

- package.json
- yarn.lock
Fixes #349 - Talked with @rmariuzzo on slack to get a new version of his Chronos library on npm, that fixes the console warning regarding unknown props.
> Fixing Chronos library warning on console

- .travis.yml
> Update travis.yml to use node v6

- app/components/Goals.jsx
- app/components/Skill.jsx
- app/components/__tests__/AddGoalsModal.spec.js
- app/components/__tests__/Goals.spec.js
- app/components/__tests__/Menu.spec.js
- app/components/__tests__/Path.spec.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skill.spec.js
- app/components/__tests__/Skills.spec.js
- app/components/__tests__/UserCard.spec.js
We had at least 15 to 20 warnings when running the tests. A lot of them were from missing/wrong props. Now we are clean. :)
> Fixing all warnings in tests

- .eslintrc
- app/components/UserCard.jsx
- app/services/slackService.js
- increase `max-len` limit from 100 to 120,
- fix linting errors #366
> Fix linting

- app/components/GoalCard.jsx
> Loading flag default "false" value - fixes #372

- CONTRIBUTING.md
* Updated broken links for some resources with correct ones
* Added more handy links for squashing commits docs
* Used `yarn` commands in favour of old `npm` ones
> Update CONTRIBUTING.md - fixes #0

- app/components/AddExistingGoalsModal.jsx
- app/components/Profile.jsx
Refactoring #374.
Details in comments below...
> WIP - Refactoring #374

- app/actions/SkillActions.js
- app/components/Skill.jsx
- app/containers/SkillContainer.js
- app/reducers/skillsReducer.js
One vote per user is allowed both by backend and frontend. Once voted, the thumb button is disabled.
> Add ability to add/remove vote for the resource - fixes #291

- deploy.sh
> Fix slack bot url environment variable

- app/components/Profiles.jsx
- app/components/__tests__/Profiles.spec.js
- app/containers/ProfilesContainer.js
Fixes #400 
**Additionally:**
- adds Loader to Profiles,
- displays a message if no profiles are found,
- changes to a specific lodash method import,
> Fix "Search by Skill" in Profiles page - #400

- app/components/Skill.jsx
Like #393 - in `Skills.jsx` there are also `props.params` (from react-router) that need to be watched for changes.
> Reload skill data on slug change - #393

- app/components/Skill.jsx
> Fix propTypes warnings in Skill component - fixes #397

- app/components/AddExistingGoalsModal.jsx
- app/components/Profile.jsx
- app/containers/ProfileContainer.js
- app/reducers/profilesReducer.js
- app/reducers/userReducer.js
Fixes #393.
**Changes:**
- loading data not only on component mount, but also when props has changed (`params.userId`),
- displaying loader if any actions is still in progress,
- fixing some `isLoading` flags,
> Reload user data on profile change - #393

- app/components/Profiles.jsx
Selecting someone's name (hitting enter) on the search box moves you directly to that person's profile page.
Fixes #402
> Add searching by skill or name - fixes #402

- app/actions/PathsActions.js
- app/components/GoalCard.jsx
- app/components/Path.jsx
- app/components/Profile.jsx
- app/components/Profiles.jsx
- app/components/__tests__/Path.spec.js
> Fix wrong user #405

- app/actions/AnnouncementActions.js
- app/actions/NewsActions.js
- app/components/AddGoalsModal.jsx
- app/components/AddSkillsModal.jsx
- app/components/CuratedPaths.jsx
- app/components/Dashboard.jsx
- app/components/Goals.jsx
- app/components/NotificationBar.jsx
- app/components/Path.jsx
- app/components/Skill.jsx
- app/components/Skills.jsx
- app/components/__tests__/AddGoalsModal.spec.js
- app/components/__tests__/Goals.spec.js
- app/components/__tests__/Path.spec.js
- app/components/__tests__/PathHeader.spec.js
- app/components/__tests__/Profiles.spec.js
- app/components/__tests__/Skill.spec.js
- app/components/__tests__/Skills.spec.js
- app/constants/errors.js
- app/containers/Menu.js
- app/helpers/authHelper.js
- app/reducers/pathsReducer.js
- app/services/authService.js
- app/services/slackService.js
- app/testUtils/fixtures/index.js
- app/testUtils/fixtures/path.js
> Direct import of lodash helpers

- deploy.sh
> Fix memory limit from hard to soft

- app/components/GoalCard.jsx
Marking cards visually as in-progress when they have a dueDate set and aren't achieved.
> Add in progress status for cards

- app/actions/PathsActions.js
- app/components/AddGoalsModal.jsx
- app/components/__tests__/AddGoalsModal.spec.js
> Use first path as default when adding custom goal - fixes #418

- app/components/PathHeader.jsx
> Fix default path name - fixes #429

- app/actions/SkillActions.js
- app/components/Skill.jsx
- app/components/__tests__/Skill.spec.js
- app/containers/SkillContainer.js
- app/reducers/skillsReducer.js
- app/testUtils/fixtures/index.js
- app/testUtils/fixtures/vote.js
One thing missing, but I would add it in a separate `quick-win` is the fact that when you vote you have to refresh - the vote count and upvoted highlihts are updated in the state but the view doesn't refresh I don't know why. Other than that listing votes and voting is 👌
> Refactor adding and listing votes

- app/components/GoalCard.jsx
> Fixing broken GoalCard component

- app/reducers/__test__/skillsReducer.spec.js
- app/reducers/skillsReducer.js
-Fix mutable update on Skill reducer
-Add test for updating the vote list
> Update Vote State - Fixes #442

- app/components/GoalsModal.jsx
**Problem**
Need a Due Date Clear option.
**Solution**
Added a Due Date Clear Button
> add due date clear button - fixes #426

- app/components/__tests__/GoalCard.spec.js
[This commit](https://github.com/x-team/unleash/commit/fc7dae9f077daff18f6b9342b7dc08ceec40a830) broke unit tests. This PR updates them to correspond to the new button setup.
> Update GoalCard tests to include new Modal Action buttons
